FROM node:20-slim

RUN apt-get update && apt-get install -y \
    ca-certificates \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

EXPOSE 8080

ENV TZ=Asia/Shanghai

CMD ["./tl-monitor-server"]
